### ISSUE TITLE
Shelly Button discovered but input 0 not subscribed properly

### ISSUE THREAD

**Issue by gobigdave** [bieniu/ha-shellies-discovery#360]
**Describe the bug**

My Shelly Button 1 is discovered, and most of the diagnostic entities are picked up. However, the button press is not available. Looking at MQTT Info, I see the subscribed topic for the button is:

shellies/shellybutton1-483FDA6FD6F1/input/0

However, if I press the button, the topic MQTT receives is:

shellies/shellybutton1-483FDA6FD6F1/input_event/0

I am running the latest firmware in the button (20221027-094235](tel:20221027-094235)/v1.12.1-ga9117d3). HA is the latest version as well.

**Expected behavior**

I expect button presses to be picked up by HA.

**Versions:**
 - Home Assistant: 2023.1.2
 - Shellies Discovery: 2.3.0
 - Shelly device firmware: 20221027-094235](tel:20221027-094235)/v1.12.1-ga9117d3

**Shellies Discovery automation:**

```yaml

```

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
You forgot to attach the debug log.

**Comment by gobigdave** [comment]
Attaching. There are no errors when I press the button. As I said above, it looks like the script is subscribing to the wrong topic. This worked at one time.
[home-assistant.log](https://github.com/bieniu/ha-shellies-discovery/files/10397922/home-assistant.log)

**Comment by bieniu** [comment]
Everything looks good
![obraz](https://user-images.githubusercontent.com/478555/212917985-e0615115-ae2e-4338-a299-40ea4c7e2928.png)

Please show me your automation that uses `short_press` trigger.

**Comment by DrDeke** [comment]
I just set up my first Shelly Button 1 today via ha-shellies-discovery and thought I might have been having the same (or a similar) problem as described in this issue, but it now appears that things are working as intended and I was misunderstanding the expected behavior. 

The reason I thought the button press events weren't making it into Home Assistant is that the "Input 0" sensor entity for the button never updates, and always reports its state as "Unavailable". However, the relevant events do show up as triggers for automations: 

"First button" pressed
"First button" double clicked
"First button" triple clicked
etc

and these triggers do fire when the button is pressed in the appropriate manner.

I am not certain whether this is the same issue that gobigdave is having, but I thought I'd mention it in case it helps.

**Comment by bieniu** [comment]
Yes, inputs generate events so device automation triggers are created for them. Input entities are disabled by default.
