### ISSUE TITLE
HACS 0.26.0 support

### ISSUE THREAD

**Issue by gerliczky** [bieniu/ha-shellies-discovery#62]
The repositoy cannot be added to HACS. I get the following error message:

> Repostitory structure for 0.26.0 is not compliant

It would be also nice to see this repo in the default HACS repository list.

**Comment by bieniu** [comment]
https://hacs.xyz/docs/default_repositories#python-scripts

**Comment by Edo78** [comment]
Once I read this issue I was even more confused ... If this repo is officially supported why HACS give that answer ...
I think the link you should provide (even in the README) is this one https://hacs.xyz/docs/categories/python_scripts

**Comment by bieniu** [comment]
The second sentence of the README file says that this is `python_script`, not integration.

**Comment by Edo78** [comment]
You are right and I don't want to argue with the one that made this wonderful script.
I'm just want to point out that I have to put `pythons_script:` in my `configuration.yaml` but I also have to create the directory `python_scripts` (I'm not sure if I removed it or if HA core doesn't create it) but just the edit to the configuration isn't enought.

**Comment by bieniu** [comment]
The script's documentation links to the `python_script` documentation page. Everything you need is written there. I find it unnecessary to rewrite this in the script documentation. I realize that many HA users haven't used `python_script` before, but what can I do about it?

**Comment by Edo78** [comment]
Maybe a rewording can help ... something like "This script needs the python_script component to be enabled as specified in the official guide. You really need this".

I learned it the hard way (totally my fault in trying to skip some steps) so I don't need any editing. I was just trying to help to spread your script even further because a lot of user haven't used `python_script`, can't figure how it works and go somewhere else and it's a pity because your script really rocks and deserve some love.

**Comment by bieniu** [comment]
OK I'll try to change that. Of course, if you want to change the docs, PR is welcome.

**Comment by Edo78** [comment]
Then I'll think about a good way to phrase that and I'll open a PR
