### ISSUE TITLE
Unavailabe RSSI & SSID

### ISSUE THREAD

**Issue by Edo78** [bieniu/ha-shellies-discovery#70]
Hi,
since I installed firmware 1.8 on my shelly 1 (and updated your script) I'm getting a strange beahviour.
Sometimes the two entities (for RSSI and SSID) became `unavailable` even if the shelly itself is online and every other entities created by your script works fine.
I even checked in the MQTT broker and I found the RSSI and SSID right there.

It looks like this issue temporarely disappear every time I restart HA.

**Comment by bieniu** [comment]
Unfortunately, this is due to the way Shellies sends the `info` topic.
In the case of battery-powered devices, the solution is to send the topic `info` after connecting to the MQTT broker. Look here: https://www.facebook.com/groups/1686781668087857/permalink/3029310427168301/
For the remaining devices, it helps to increase the frequency of the `announce` automation startup. I recommend running it every hour.

**Comment by Edo78** [comment]
I just noticed that the minimal configuration was changed since I installed your script the first time.
Now the `announce` will be executed every hour.

Thank you

**Comment by bieniu** [comment]
> the minimal configuration was changed since I installed your script

I think I forgot to write about it in the changelog 🤔
